CREATE TABLE IF NOT EXISTS statistics (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app         varchar(50) NOT NULL,
    uri         varchar(255) NOT NULL,
    ip          varchar(45) NOT NULL,
    timestamp   TIMESTAMP NOT NULL
);